-- Table: BOUTEILLE

-- DROP TABLE IF EXISTS BOUTEILLE;

CREATE TABLE BOUTEILLE
(
  id BIGSERIAL NOT NULL,
  nom CHARACTER VARYING(250) NOT NULL,
  nom_chateau CHARACTER VARYING(250),
  millesime INTEGER NOT NULL,
  contenance INTEGER NOT NULL,
  CONSTRAINT bouteille_pk PRIMARY KEY (id)
)
WITH (
OIDS = FALSE
);
ALTER TABLE BOUTEILLE
OWNER TO postgres;