-- Table: BOUTEILLE

-- DROP TABLE IF EXISTS BOUTEILLE;

CREATE TABLE "BOUTEILLE"
(
  "ID" BIGSERIAL NOT NULL,
  "NOM" CHARACTER VARYING(250) NOT NULL,
  "NOM_CHATEAU" CHARACTER VARYING(250),
  "MILLESIME" INTEGER NOT NULL,
  "CONTENANCE" INTEGER NOT NULL,
  CONSTRAINT bouteille_pk PRIMARY KEY ("ID")
)
WITH (
OIDS = FALSE
);
ALTER TABLE BOUTEILLE
OWNER TO postgres;